# Generated by Django 2.0 on 2018-09-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_photo',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
